services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgis
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: samuel
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: septa_db
    volumes:
      - pgdata:/var/lib/postgresql/data 

volumes:
  pgdata: